@ECHO OFF

:: Assign all Path variables
SET PROJECT_WS=%~dp0
SET PROJECT_LIB=%PROJECT_WS%libs
SET PROJECT_LIB_PAGE_OBJECT=%PROJECT_WS%libs\page_objects
SET PROJECT_RESOURCES=%PROJECT_WS%resources

echo %PROJECT_WS%
echo %PROJECT_LIB%
echo %PROJECT_LIB_PAGE_OBJECT%
echo %PROJECT_RESOURCES%

:: Set Path variable
setx PYTHONPATH "%PROJECT_WS%;%PROJECT_LIB%;%PROJECT_LIB_PAGE_OBJECT%;%PROJECT_RESOURCES%" /m

PAUSE